// <auto-generated />
using System;
using Alarms.Db.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Alarms.Db.Migrations
{
    [DbContext(typeof(AlarmsDbContext))]
    [Migration("20220630082546_AddFullEventsTable")]
    partial class AddFullEventsTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Alarms.Db.Entities.EventLog", b =>
                {
                    b.Property<Guid>("EventLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("EventDateTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("State")
                        .HasColumnType("bit");

                    b.Property<Guid>("TagDataId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("EventLogId");

                    b.HasIndex("TagDataId");

                    b.ToTable("EventLogs");
                });

            modelBuilder.Entity("Alarms.Db.Entities.FullEvents", b =>
                {
                    b.Property<Guid>("FullEventsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Duration")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("EventEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EventStart")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("TagDataId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("FullEventsId");

                    b.HasIndex("TagDataId");

                    b.ToTable("FullEvents");
                });

            modelBuilder.Entity("Alarms.Db.Entities.TagData", b =>
                {
                    b.Property<Guid>("TagDataId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TagName")
                        .HasColumnType("varchar(50)");

                    b.HasKey("TagDataId");

                    b.ToTable("TagDatas");
                });

            modelBuilder.Entity("Alarms.Db.Entities.EventLog", b =>
                {
                    b.HasOne("Alarms.Db.Entities.TagData", "TagData")
                        .WithMany("EventLog")
                        .HasForeignKey("TagDataId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TagData");
                });

            modelBuilder.Entity("Alarms.Db.Entities.FullEvents", b =>
                {
                    b.HasOne("Alarms.Db.Entities.TagData", "TagData")
                        .WithMany("FullEvents")
                        .HasForeignKey("TagDataId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TagData");
                });

            modelBuilder.Entity("Alarms.Db.Entities.TagData", b =>
                {
                    b.Navigation("EventLog");

                    b.Navigation("FullEvents");
                });
#pragma warning restore 612, 618
        }
    }
}
