// <auto-generated />
using System;
using Alarms.Db.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Alarms.Db.Migrations
{
    [DbContext(typeof(AlarmsDbContext))]
    partial class AlarmsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Alarms.Db.Entities.EventLog", b =>
                {
                    b.Property<Guid>("EventLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("EventDateTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("State")
                        .HasColumnType("bit");

                    b.Property<Guid>("TagDataId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("EventLogId");

                    b.ToTable("EventLogs", (string)null);
                });

            modelBuilder.Entity("Alarms.Db.Entities.TagData", b =>
                {
                    b.Property<Guid>("TagDataId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TagName")
                        .HasColumnType("varchar(50)");

                    b.HasKey("TagDataId");

                    b.ToTable("TagDatas", (string)null);
                });

            modelBuilder.Entity("Alarms.Db.Entities.TagData", b =>
                {
                    b.HasOne("Alarms.Db.Entities.EventLog", "EventLog")
                        .WithOne("TagData")
                        .HasForeignKey("Alarms.Db.Entities.TagData", "TagDataId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EventLog");
                });

            modelBuilder.Entity("Alarms.Db.Entities.EventLog", b =>
                {
                    b.Navigation("TagData");
                });
#pragma warning restore 612, 618
        }
    }
}
